<?php
/***CONFIGURATOR***/
$sugar_config['disable_persistent_connections'] = false;
$sugar_config['dbconfigoption']['collation'] = 'utf8_general_ci';
$sugar_config['default_locale_name_format'] = 'f l';
$sugar_config['default_theme'] = 'SuiteP';
$sugar_config['disabled_themes'] = '';
$sugar_config['default_language'] = 'es_ES';
$sugar_config['disabled_languages'] = '';
$sugar_config['developerMode'] = false;
$sugar_config['default_module_favicon'] = false;
$sugar_config['dashlet_auto_refresh_min'] = '30';
$sugar_config['stack_trace_errors'] = false;
$sugar_config['logger']['level'] = 'debug';
$sugar_config['logger']['file']['name'] = 'wisecrm';
$sugar_config['logger']['file']['suffix'] = '%d_%m';
$sugar_config['default_decimal_seperator'] = ',';
$sugar_config['default_number_grouping_seperator'] = '.';
$sugar_config['passwordsetting']['SystemGeneratedPasswordON'] = '1';
$sugar_config['passwordsetting']['forgotpasswordON'] = '0';
$sugar_config['passwordsetting']['linkexpirationtime'] = '24';
$sugar_config['passwordsetting']['linkexpirationtype'] = '60';
$sugar_config['passwordsetting']['systexpirationtime'] = '4';
$sugar_config['passwordsetting']['systexpirationtype'] = '30';
$sugar_config['passwordsetting']['oneupper'] = '1';
$sugar_config['passwordsetting']['onelower'] = '1';
$sugar_config['passwordsetting']['onenumber'] = '1';
$sugar_config['passwordsetting']['onespecial'] = '1';
$sugar_config['SAML_loginurl'] = '';
$sugar_config['SAML_logouturl'] = '';
$sugar_config['SAML_X509Cert'] = '';
$sugar_config['authenticationClass'] = '';
$sugar_config['email_xss'] = 'YToxMzp7czo2OiJhcHBsZXQiO3M6NjoiYXBwbGV0IjtzOjQ6ImJhc2UiO3M6NDoiYmFzZSI7czo1OiJlbWJlZCI7czo1OiJlbWJlZCI7czo0OiJmb3JtIjtzOjQ6ImZvcm0iO3M6NToiZnJhbWUiO3M6NToiZnJhbWUiO3M6ODoiZnJhbWVzZXQiO3M6ODoiZnJhbWVzZXQiO3M6NjoiaWZyYW1lIjtzOjY6ImlmcmFtZSI7czo2OiJpbXBvcnQiO3M6ODoiXD9pbXBvcnQiO3M6NToibGF5ZXIiO3M6NToibGF5ZXIiO3M6NDoibGluayI7czo0OiJsaW5rIjtzOjY6Im9iamVjdCI7czo2OiJvYmplY3QiO3M6MzoieG1wIjtzOjM6InhtcCI7czo2OiJzY3JpcHQiO3M6Njoic2NyaXB0Ijt9';
$sugar_config['email_default_delete_attachments'] = true;
$sugar_config['securitysuite_filter_user_list'] = true;
$sugar_config['securitysuite_inherit_assigned'] = true;
$sugar_config['securitysuite_popup_select'] = true;
$sugar_config['securitysuite_inbound_email'] = true;
/***CONFIGURATOR***/